services: 
  my-nginx-service:
    image: nginx 
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:8080
    environment: 
      - PORT=8080
    volumes:
      - mywebdata:/app/data
  my-redis-service: 
    image: redis 
    volumes:
      - myredisdata:/data

volumes: 
  mywebdata: 
  myredisdata: