name: Run Ansible
on:
  workflow_dispatch:
jobs: 
  run-playbooks:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python 3
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Upgrade Pip & Install Ansible
        run: |
          python -m pip install --upgrade pip 
          python -m pip install ansible
      - name: Implement the Private SSH Key 
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa 
          chmod 600 ~/.ssh/id_rsa
      - name: Ansible Inventory File for Remote host 
        working-directory: ./devops/ansible/ 
        run: |
          echo "${{ secrets.AKAMAI_INSTANCE_IP_ADDRESS }}" >> inventory.ini      
      - name: Ping Ansible Hosts 
        working-directory: ./devops/ansible/ 
        run: |
          ansible all -m ping
      - name: Run Ansible Playbooks
        working-directory: ./devops/ansible/ 
        run: |
          ansible-playbook install-nginx.yaml
      # - name: Deploy Python via Ansible
      #   working-directory: ./devops/ansible/ 
      #   run: |
      #     ansible-playbook deploy-python.yaml